---
name: 'Build and test xdp-skeleton'

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/build-skip.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/build-skip.yml'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: xdp-skeleton-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@e600775e527acba2317260cadb64b7e19efd5362

    - name: Build the image
      working-directory: src
      run: make
